apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus-server
    spec:
      serviceAccountName: prometheus
      containers:
        - name: sidecar
          image: gcr.io/stackdriver-prometheus/stackdriver-prometheus-sidecar:0.4.3
          args:
          - "--stackdriver.project-id=gcdeveloper"
          - "--prometheus.wal-directory=/prometheus/wal"
          - "--prometheus.api-address=http://127.0.0.1:9090"
          - "--stackdriver.kubernetes.location=us-central1"
          - "--stackdriver.kubernetes.cluster-name=anthos-poc"
          ports:
          - name: sidecar
            containerPort: 9091
          volumeMounts:
          - name: prometheus-storage-volume
            mountPath: /prometheus
        - name: prometheus
          image: prom/prometheus:v2.6.1
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
            - name: prometheus-storage-volume
              mountPath: /prometheus/
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-server-conf
        - name: prometheus-storage-volume
          emptyDir: {}
